Index: test_deferred.py
===================================================================
--- test_deferred.py	(revision 37786)
+++ test_deferred.py	(working copy)
@@ -157,38 +157,56 @@
 
     def test_pass(self):
         """
-        C{runTest} is run with test_pass as argument. This test fails
-        if C{runTest} fails
+        This test fails if it is unable to pass the deferred object.
+
         """
         result = self.runTest('test_pass')
         self.failUnless(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
 
     def test_passGenerated(self):
+        """
+        This test fails if passing the generated deferred fails.
+        """
         result = self.runTest('test_passGenerated')
         self.failUnless(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
         self.failUnless(detests.DeferredTests.touched)
 
     def test_fail(self):
+        """
+        The test fails if the returned deferred fails.
+        """
         result = self.runTest('test_fail')
         self.failIf(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
         self.assertEqual(len(result.failures), 1)
 
     def test_failureInCallback(self):
+        """
+        This test fails if a failure occurs when 
+        the deferred object makes a callback.
+        """
         result = self.runTest('test_failureInCallback')
         self.failIf(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
         self.assertEqual(len(result.failures), 1)
 
     def test_errorInCallback(self):
+        """
+        Fails when an error occurs during callback of a 
+        deferred object. 
+        """
         result = self.runTest('test_errorInCallback')
         self.failIf(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
         self.assertEqual(len(result.errors), 1)
 
     def test_skip(self):
+        """
+        This test fails if an error occur when a deferred 
+        is skipped.
+        """
         result = self.runTest('test_skip')
         self.failUnless(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
@@ -196,6 +214,10 @@
         self.failIf(detests.DeferredTests.touched)
 
     def test_todo(self):
+        """
+        Fails if the deferred object confront any expected
+        failure
+        """
         result = self.runTest('test_expectedFailure')
         self.failUnless(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
@@ -204,6 +226,10 @@
         self.assertEqual(len(result.expectedFailures), 1)
 
     def test_thread(self):
+        """
+        This test fails if a error occurs with the thread 
+        with which the deferred is working.
+        """
         result = self.runTest('test_thread')
         self.assertEqual(result.testsRun, 1)
         self.failUnless(result.wasSuccessful(), result.errors)
@@ -212,23 +238,39 @@
 
 class TestTimeout(TestTester):
     def getTest(self, name):
+        """
+        The argument passed to this test case is sent to C{TimeoutTests}.
+        """
         return detests.TimeoutTests(name)
 
     def _wasTimeout(self, error):
+        """
+        Tests if timeout has occured or not and return failure if timed out.
+        """
         self.assertEqual(error.check(defer.TimeoutError),
                              defer.TimeoutError)
 
     def test_pass(self):
+        """
+        This test fails if it is unable to pass the deferred object.
+        """
         result = self.runTest('test_pass')
         self.failUnless(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
 
     def test_passDefault(self):
+        """
+        This test fails if it is unable to pass the deferred object 
+        with default values.
+        """
         result = self.runTest('test_passDefault')
         self.failUnless(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
 
     def test_timeout(self):
+        """
+        Fails if the deferred object reaches its timeout value.
+        """
         result = self.runTest('test_timeout')
         self.failIf(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
@@ -236,6 +278,9 @@
         self._wasTimeout(result.errors[0][1])
 
     def test_timeoutZero(self):
+        """
+        Fails of the timeout value of the deferred reaches zero.
+        """
         result = self.runTest('test_timeoutZero')
         self.failIf(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
@@ -243,12 +288,20 @@
         self._wasTimeout(result.errors[0][1])
 
     def test_skip(self):
+        """
+        This test fails if an error occur when a deferred object  
+        is skipped.
+        """
         result = self.runTest('test_skip')
         self.failUnless(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
         self.assertEqual(len(result.skips), 1)
 
     def test_todo(self):
+        """
+        Test fails of the deferred object faces any expected failure.
+        Also check if timeout has occured.
+        """
         result = self.runTest('test_expectedFailure')
         self.failUnless(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
@@ -256,12 +309,20 @@
         self._wasTimeout(result.expectedFailures[0][1])
 
     def test_errorPropagation(self):
+        """
+        Test fails if an error occurs during the propagation
+        of errors in the callbacks.
+        """
         result = self.runTest('test_errorPropagation')
         self.failIf(result.wasSuccessful())
         self.assertEqual(result.testsRun, 1)
         self._wasTimeout(detests.TimeoutTests.timedOut)
 
     def test_classTimeout(self):
+        """
+        Loads C{TestLoader} and perform C{TestResult} from C{TestsFromTestCase}.
+        Fails if it returns failure
+        """
         loader = pyunit.TestLoader()
         suite = loader.loadTestsFromTestCase(detests.TestClassTimeoutAttribute)
         result = reporter.TestResult()
@@ -270,6 +331,11 @@
         self._wasTimeout(result.errors[0][1])
 
     def test_callbackReturnsNonCallingDeferred(self):
+        """
+        C{callLater} is called as argument that generates a delayed call back. 
+        C{runTest} is run with test_callButNeverCallback as argument.
+        Fails if it returns any failure.
+        """
         #hacky timeout
         # raises KeyboardInterrupt because Trial sucks
         from twisted.internet import reactor
