To reproduce the bug described in the ticket, download

client.py
server.py
resources.py

and put them in a single directory. Then run server.py. Then run client.py. You will see some brief output on the client console. Note that the id reported by the RemoteCache is different when it is checked from within an observe_* method. This is the bug.

