2004/11/21 19:09 EST [-] Log opened.
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testColorAttributes <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testCursorBackward <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testCursorDown <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testCursorForward <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testCursorPositioning <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testCursorUp <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testEraseDisplay <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testEraseLine <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testEraseToDisplayBeginning <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testEraseToDisplayEnd <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testEraseToLineBeginning <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testEraseToLineEnd <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testGraphicRendition <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testIndex <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testInitialState <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testInsert <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testLineDeletion <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testLineInsertion <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testNextLine <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testOvertype <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testReverseIndex <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testSaveCursor <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testShifting <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testSimpleWriting <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testSingleShifts <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testWritingInTheMiddle <--
2004/11/21 19:09 EST [-] --> test_helper.BufferTestCase.testWritingWrappedAtEndOfLine <--
2004/11/21 19:09 EST [-] --> test_insults.ClientByteGroups.testBytePairs <--
2004/11/21 19:09 EST [-] --> test_insults.ClientByteGroups.testByteQuads <--
2004/11/21 19:09 EST [-] --> test_insults.ClientByteGroups.testByteQuints <--
2004/11/21 19:09 EST [-] --> test_insults.ClientByteGroups.testByteSexes <--
2004/11/21 19:09 EST [-] --> test_insults.ClientByteGroups.testByteTriples <--
2004/11/21 19:09 EST [-] --> test_insults.ClientByteGroups.testSingleBytes <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testCharacterSet <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testCursor <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testCursorPosition <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testErasure <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testHeightAndWidth <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testIndex <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testKeypadMode <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testLineDeletion <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testLineInsertion <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testModes <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testReset <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testScrollRegion <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testShifting <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testSimpleCardinals <--
2004/11/21 19:09 EST [-] --> test_insults.ClientControlSequences.testSingleShifts <--
2004/11/21 19:09 EST [-] --> test_insults.ServerByteGroupings.testBytePairs <--
2004/11/21 19:09 EST [-] --> test_insults.ServerByteGroupings.testByteQuads <--
2004/11/21 19:09 EST [-] --> test_insults.ServerByteGroupings.testByteQuints <--
2004/11/21 19:09 EST [-] --> test_insults.ServerByteGroupings.testByteSexes <--
2004/11/21 19:09 EST [-] --> test_insults.ServerByteGroupings.testByteTriples <--
2004/11/21 19:09 EST [-] --> test_insults.ServerByteGroupings.testSingleBytes <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testDownArrow <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF1 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF10 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF11 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF12 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF2 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF3 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF4 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF5 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF6 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF7 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF8 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testF9 <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testLeftArrow <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testRightArrow <--
2004/11/21 19:09 EST [-] --> test_insults.ServerControlCharacters.testUpArrow <--
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackSSH.testClassDefinition <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackSSH.testControlC <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackSSH.testControlD <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] sending close 0
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] remote close
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending close 0
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] closed
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] remote close
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackSSH.testControlQ <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] sending close 0
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] remote close
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending close 0
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] closed
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] remote close
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackSSH.testDeferred <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackSSH.testException <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackSSH.testFunctionDefinition <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackSSH.testSimpleExpression <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackSSH.testTripleQuoteLineContinuation <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] Installing SIGCHLD signal handler.
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackStdio.testClassDefinition <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_manhole.py", line 50, in testClassDefinition
2004/11/21 19:09 EST [-]     [">>> class Foo:",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: "class Foo:\n\tdef bar(self):\n\t\tprint 'Hello, world!'\n\nFoo().bar()\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" != ">>> class Foo:\n...     def bar(self):\n...         print 'Hello, world!'\n...\n>>> Foo().bar()\nHello, world!\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackStdio.testControlC <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_manhole.py", line 70, in testControlC
2004/11/21 19:09 EST [-]     [">>> cancelled line",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: '  File "/usr/lib/python2.3/sre.py", line 228, in _compile\n    p = sre_compile.compile(pattern, flags)\n  File "/usr/lib/python2.3/sre_compile.py", line 467, in compile\n    p = sre_parse.parse(p, flags)\n  File "/usr/lib/python2.3/sre_parse.py", line 624, in parse\n    p = _parse_sub(source, pattern, 0)\n  File "/usr/lib/python2.3/sre_parse.py", line 317, in _parse_sub\n    items.append(_parse(source, state))\n  File "/usr/lib/python2.3/sre_parse.py", line 584, in _parse\n    p = _parse_sub(source, state)\n  File "/usr/lib/python2.3/sre_parse.py", line 317, in _parse_sub\n    items.append(_parse(source, state))\n  File "/usr/lib/python2.3/sre_parse.py", line 584, in _parse\n    p = _parse_sub(source, state)\n  File "/usr/lib/python2.3/sre_parse.py", line 317, in _parse_sub\n    items.append(_parse(source, state))\n  File "/usr/lib/python2.3/sre_parse.py", line 376, in _parse\n    this = source.get()\n  File "/usr/lib/python2.3/sre_parse.py", line 208, in get\n    self.__next()\n  File "/usr/lib/python2.3/sre_parse.py", line 198, in __next\n    self.index = self.index + len(char)\nKeyboardInterrupt\n' != '>>> cancelled line\nKeyboardInterrupt\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackStdio.testControlD <--
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackStdio.testControlQ <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_manhole.py", line 77, in testControlQ
2004/11/21 19:09 EST [-]     [""])
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'cancelled line\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackStdio.testDeferred <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_manhole.py", line 93, in testDeferred
2004/11/21 19:09 EST [-]     [">>> from twisted.internet import defer, reactor",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: "from twisted.internet import defer, reactor\ndef deferLater(n):\n\td = defer.Deferred()\n\treactor.callLater(n, d.callback, 'Hi!')\n\treturn d\n\ndeferLater(0.1)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" != ">>> from twisted.internet import defer, reactor\n>>> def deferLater(n):\n...     d = defer.Deferred()\n...     reactor.callLater(n, d.callback, 'Hi!')\n...     return d\n...\n>>> deferLater(0.1)\n<Deferred #0>\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackStdio.testException <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_manhole.py", line 61, in testException
2004/11/21 19:09 EST [-]     [">>> 1 / 0",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: '1 / 0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> 1 / 0\nTraceback (most recent call last):\n  File "<console>", line 1, in ?\nZeroDivisionError: integer division or modulo by zero\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackStdio.testFunctionDefinition <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_manhole.py", line 37, in testFunctionDefinition
2004/11/21 19:09 EST [-]     [">>> def foo(bar):",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'def foo(bar):\n\tprint bar\n\nfoo(42)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> def foo(bar):\n...     print bar\n...\n>>> foo(42)\n42\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackStdio.testSimpleExpression <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_manhole.py", line 20, in testSimpleExpression
2004/11/21 19:09 EST [-]     [">>> 1 + 1",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: '1 + 1\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> 1 + 1\n2\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackStdio.testTripleQuoteLineContinuation <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_manhole.py", line 27, in testTripleQuoteLineContinuation
2004/11/21 19:09 EST [-]     [">>> '''",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: "'''\n'''\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" != ">>> '''\n... '''\n'\\n'\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] Uninstalled SIGCHLD signal handler.
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackTelnet.testClassDefinition <--
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackTelnet.testControlC <--
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackTelnet.testControlD <--
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackTelnet.testControlQ <--
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackTelnet.testDeferred <--
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackTelnet.testException <--
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackTelnet.testFunctionDefinition <--
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackTelnet.testSimpleExpression <--
2004/11/21 19:09 EST [-] --> test_manhole.ManholeLoopbackTelnet.testTripleQuoteLineContinuation <--
2004/11/21 19:09 EST [-] --> test_mixin.BufferingTest.testBuffering <--
2004/11/21 19:09 EST [-] --> test_recvline.Arrows.testBackspace <--
2004/11/21 19:09 EST [-] --> test_recvline.Arrows.testDelete <--
2004/11/21 19:09 EST [-] --> test_recvline.Arrows.testEnd <--
2004/11/21 19:09 EST [-] --> test_recvline.Arrows.testHome <--
2004/11/21 19:09 EST [-] --> test_recvline.Arrows.testHorizontalArrows <--
2004/11/21 19:09 EST [-] --> test_recvline.Arrows.testInsert <--
2004/11/21 19:09 EST [-] --> test_recvline.Arrows.testNewline <--
2004/11/21 19:09 EST [-] --> test_recvline.Arrows.testPrintableCharacters <--
2004/11/21 19:09 EST [-] --> test_recvline.Arrows.testTypeover <--
2004/11/21 19:09 EST [-] --> test_recvline.Arrows.testVerticalArrows <--
2004/11/21 19:09 EST [-] --> test_recvline.HistoricRecvlineLoopbackSSH.testDownArrow <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_recvline.HistoricRecvlineLoopbackSSH.testUpArrow <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] Installing SIGCHLD signal handler.
2004/11/21 19:09 EST [-] --> test_recvline.HistoricRecvlineLoopbackStdio.testDownArrow <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 522, in testDownArrow
2004/11/21 19:09 EST [-]     [">>> first line",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'first line\nsecond line\n^[[A^[[A^[[B\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> first line\nfirst line\n>>> second line\nsecond line\n>>> second line\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.HistoricRecvlineLoopbackStdio.testUpArrow <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 515, in testUpArrow
2004/11/21 19:09 EST [-]     [">>> first line",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'first line\n^[[A\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> first line\nfirst line\n>>> first line\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] Uninstalled SIGCHLD signal handler.
2004/11/21 19:09 EST [-] --> test_recvline.HistoricRecvlineLoopbackTelnet.testDownArrow <--
2004/11/21 19:09 EST [-] --> test_recvline.HistoricRecvlineLoopbackTelnet.testUpArrow <--
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackSSH.testBackspace <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackSSH.testDelete <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackSSH.testEnd <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackSSH.testHome <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 489, in testHome
2004/11/21 19:09 EST [-]     [">>> home line",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: '>>> homeblah line\nhome line\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> home line\nhome line\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackSSH.testInsert <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackSSH.testLeftArrow <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 447, in testLeftArrow
2004/11/21 19:09 EST [-]     [">>> first xxxx",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: '>>> first xxxxline\nfirst xxxx\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> first xxxx\nfirst xxxx\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackSSH.testRightArrow <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 454, in testRightArrow
2004/11/21 19:09 EST [-]     [">>> right lixx",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: '>>> right lixxne\nright lixx\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> right lixx\nright lixx\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackSSH.testSimple <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackSSH.testTypeover <--
2004/11/21 19:09 EST [serverTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [serverTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [serverTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] kex alg, key alg: diffie-hellman-group1-sha1 ssh-rsa
2004/11/21 19:09 EST [clientTransport] server->client: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] client->server: aes256-ctr hmac-sha1 none
2004/11/21 19:09 EST [clientTransport] starting service ssh-userauth
2004/11/21 19:09 EST [serverTransport] starting service ssh-userauth
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth none
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] can continue with: ['password']
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] trying to auth with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser trying auth password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] testuser authenticated with password
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('TestTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] starting service ssh-connection
2004/11/21 19:09 EST [SSHService ssh-userauth on LoopbackRelay('SSHServerTransport')] opening channel 0 with 131072 32768
2004/11/21 19:09 EST [SSHService ssh-connection on LoopbackRelay('TestTransport')] got channel session request
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] channel open
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request pty-req
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('SSHServerTransport')] sending request shell
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] pty request: vt102 (24L, 80L, 0L, 0L)
2004/11/21 19:09 EST [SSHChannel session (0) on SSHService ssh-connection on LoopbackRelay('TestTransport')] getting shell
2004/11/21 19:09 EST [-] Installing SIGCHLD signal handler.
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackStdio.testBackspace <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 461, in testBackspace
2004/11/21 19:09 EST [-]     [">>> second xxxx",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'second line\x08 \x08\x08 \x08\x08 \x08\x08 \x08xxxx\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> second xxxx\nsecond xxxx\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackStdio.testDelete <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 468, in testDelete
2004/11/21 19:09 EST [-]     [">>> delete line",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'delete xxxx^[[D^[[D^[[D^[[D^[[3~^[[3~^[[3~^[[3~line\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> delete line\ndelete line\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackStdio.testEnd <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 496, in testEnd
2004/11/21 19:09 EST [-]     [">>> end line",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'end ^[[D^[[D^[[D^[[D^[[4~line\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> end line\nend line\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackStdio.testHome <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 489, in testHome
2004/11/21 19:09 EST [-]     [">>> home line",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'blah line^[[1~home\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> home line\nhome line\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackStdio.testInsert <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 475, in testInsert
2004/11/21 19:09 EST [-]     [">>> third line",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'third ine^[[D^[[D^[[D^[[2~l\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> third line\nthird line\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackStdio.testLeftArrow <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 447, in testLeftArrow
2004/11/21 19:09 EST [-]     [">>> first xxxx",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'first line^[[D^[[D^[[D^[[Dxxxx\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> first xxxx\nfirst xxxx\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackStdio.testRightArrow <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 454, in testRightArrow
2004/11/21 19:09 EST [-]     [">>> right lixx",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'right line^[[D^[[D^[[D^[[D^[[C^[[Cxx\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> right lixx\nright lixx\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackStdio.testSimple <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 442, in testSimple
2004/11/21 19:09 EST [-]     [">>> first line"])
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'first line\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> first line\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackStdio.testTypeover <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 482, in testTypeover
2004/11/21 19:09 EST [-]     [">>> fourth line",
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_recvline.py", line 328, in _test
2004/11/21 19:09 EST [-]     '\n'.join(lines) +
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: 'fourth xine^[[D^[[D^[[D^[[D^[[2~^[[2~l\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' != '>>> fourth line\nfourth line\n>>>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] Uninstalled SIGCHLD signal handler.
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackTelnet.testBackspace <--
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackTelnet.testDelete <--
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackTelnet.testEnd <--
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackTelnet.testHome <--
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackTelnet.testInsert <--
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackTelnet.testLeftArrow <--
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackTelnet.testRightArrow <--
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackTelnet.testSimple <--
2004/11/21 19:09 EST [-] --> test_recvline.RecvlineLoopbackTelnet.testTypeover <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testAbortOutput <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testAcceptDo <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testAcceptDont <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testAcceptWill <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testAcceptWont <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testAcceptedDisableRequest <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testAcceptedEnableRequest <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testAreYouThere <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testBoundarySubnegotiation <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testBreak <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testDataMark <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testEraseCharacter <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testEraseLine <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testGoAhead <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testIACEscape <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testIgnoreDo <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testIgnoreDont <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testIgnoreWill <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testIgnoreWont <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testInterrupt <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testLostConnectionFailsDeferreds <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testNegotiationBlocksFurtherNegotiation <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testNewlineHandling <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testNoOperation <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testRefuseDo <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testRefuseWill <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testRefusedEnableRequest <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testRegularBytes <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testSubnegotiation <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testSubnegotiationWithEmbeddedSE <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testSuperfluousDisableRequestRaises <--
2004/11/21 19:09 EST [-] --> test_telnet.TelnetTestCase.testSuperfluousEnableRequestRaises <--
2004/11/21 19:09 EST [-] --> test_text.Serialization.testBackground <--
2004/11/21 19:09 EST [-] --> test_text.Serialization.testBlink <--
2004/11/21 19:09 EST [-] --> test_text.Serialization.testBold <--
2004/11/21 19:09 EST [-] --> test_text.Serialization.testComplexStructure <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_text.py", line 86, in testComplexStructure
2004/11/21 19:09 EST [-]     "\x1b[1;31;46mForeground Red, Background Cyan, Bold"
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: '\x1b[1;31;46mForeground Red, Background Cyan, Bold\x1b[1;5;31;46mBlinking\x1b[0;31;46mForeground Red, Background Cyan, normal\x1b[1;32;46mForeground Green, Background Cyan, Bold' != '\x1b[1;31;46mForeground Red, Background Cyan, Bold\x1b[5mBlinking\x1b[0;31;46mForeground Red, Background Cyan, normal\x1b[1;32;46mForeground Green, Background Cyan, Bold'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_text.Serialization.testForeground <--
2004/11/21 19:09 EST [-] --> test_text.Serialization.testMinus <--
2004/11/21 19:09 EST [-] --> test_text.Serialization.testNesting <--
2004/11/21 19:09 EST [-] Traceback (most recent call last):
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 842, in run
2004/11/21 19:09 EST [-]     orig(tci)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in __call__
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 395, in _runWithWarningFilters
2004/11/21 19:09 EST [-]     return f(*a, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/runner.py", line 321, in <lambda>
2004/11/21 19:09 EST [-]     lambda :util.wait(defer.maybeDeferred(self.original, *a, **kw),
2004/11/21 19:09 EST [-] --- <exception caught here> ---
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/internet/defer.py", line 117, in maybeDeferred
2004/11/21 19:09 EST [-]     result = f(*args, **kw)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/sandbox/exarkun/manhole/test_text.py", line 42, in testNesting
2004/11/21 19:09 EST [-]     '\x1b[1mHello, \x1b[4mworld.')
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/unittest.py", line 415, in <lambda>
2004/11/21 19:09 EST [-]     failUnlessEqual = lambda self, a, b, msg=None: failUnlessEqual(a, b, msg)
2004/11/21 19:09 EST [-]   File "/home/exarkun/projects/python/Twisted/trunk/twisted/trial/assertions.py", line 77, in failUnlessEqual
2004/11/21 19:09 EST [-]     raise FailTest, (msg or '%r != %r' % (first, second))
2004/11/21 19:09 EST [-] twisted.trial.assertions.FailTest: '\x1b[1mHello, \x1b[1;4mworld.' != '\x1b[1mHello, \x1b[4mworld.'
2004/11/21 19:09 EST [-] None
2004/11/21 19:09 EST [-] --> test_text.Serialization.testReverseVideo <--
2004/11/21 19:09 EST [-] --> test_text.Serialization.testTrivial <--
2004/11/21 19:09 EST [-] --> test_text.Serialization.testUnderline <--
